{% set version = "0.5.1" %}

package:
  name: oceanval
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/o/oceanval/oceanval-{{ version }}.tar.gz
  sha256: 70e0e564b95109d7e09fd35e863627ec25cb40b627d399fdd76257c4e29b0c69


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools-git
    - setuptools
  run:
    - python >={{ python_min }}
    - dill
    - multiprocess
    - fiona
    - jupyter-book  <=1.0.4
    - jupytext
    - plotnine
    - nctoolkit  >=1.2.6
    - matplotlib  >=3.10.9
    - notebook
    - nodejs  =22.23.2
    - ipykernel
    - rpy2
    - r-base
    - r-rcpp
    - r-cowplot
    - r-ggthemes
    - r-maps
    - r-plotrix
    - r-tidyverse
    - r-ggtext

test:
  imports:
    - oceanval
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://oceanval.readthedocs.io/en/
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Automated ocean model validation in Python.

extra:
  recipe-maintainers:
    - robertjwilson
