{% set version = "0.1.6" %}

package:
  name: oceanval
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/oceanval/oceanval-{{ version }}.tar.gz
  sha256: 8f0f28e6f6568b26c9e133706d0a6193fd9d31c9eadc759eb6ab9a487841ea4a


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools-git
    - setuptools
  run:
    - python >={{ python_min }}
    - dill
    - multiprocess
    - fiona
    - jupyter-book  <=1.0.4
    - jupytext
    - plotnine
    - nctoolkit
    - notebook
    - ipykernel
    - rpy2
    - r-base
    - r-rcpp
    - r-cowplot
    - r-ggthemes
    - r-maps
    - r-plotrix
    - r-tidyverse
    - r-ggtext

test:
  imports:
    - oceanval
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://oceanval.readthedocs.io/en/
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Automated ocean model validation in Python.

extra:
  recipe-maintainers:
    - robertjwilson
